# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push
  # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  infra-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
         image: ubuntuk8s/ubuntu-terraform:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: 
          path: pipeline-test
      - uses: actions/checkout@v2
        with: 
          repository: 'balu970/terraform'
          ref: 'master'
          
      # Runs a set of commands using the runners shell
      - name: infra-deploy
        run: |
          ls -la 
    #      sudo apt-get -y update; sudo apt-get -y install git curl jq python3-pip; sudo apt-get -y install wget unzip
    #      sudo pip3 install -U awscli
    #      sudo chown -R $(whoami) /usr/local/bin
    #      sudo curl -fsSL https://get.docker.com -o get-docker.sh
    #      sudo curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
    #      sudo tfswitch 0.12.23
    #      sudo wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
    #      sudo unzip sonar-scanner-cli-4.5.0.2216-linux.zip
    #      eval `ssh-agent -s`
